### ISSUE TITLE
Updating this config for Stylelint version 14

### ISSUE THREAD

**Issue by nikoladev** [chaucerbao/stylelint-config-concentric-order#24]
[Stylelint version 14][rel] has been released (it has a [migration guide][guide])

Would it be hard to update this config for the new Stylelint version?

Is there anything you would need help with?

[rel]: https://github.com/stylelint/stylelint/releases/tag/14.0.0
[guide]: https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-14.md

**Comment by chaucerbao** [comment]
Published [v5](https://www.npmjs.com/package/stylelint-config-concentric-order) with Stylelint 14 support.

**Comment by nikoladev** [comment]
Thanks!
