### ISSUE TITLE
More missing properties

### ISSUE THREAD

**Issue by daviddelusenet** [chaucerbao/stylelint-config-concentric-order#4]
Guess who's back! Great job solving my issues so far 💯 

I've some more CSS properties which are missing: `mix-blend-mode` and `isolation`.

**Comment by chaucerbao** [comment]
Gotcha covered. Added them next to `opacity`. Also added `background-blend-mode` near the other background props.

Must be nice to be able to ignore IE browsers 😄

**Comment by daviddelusenet** [comment]
Thanks man, keep up the good work!

Who needs IE anyway 😏
