### ISSUE TITLE
Stylelint v10

### ISSUE THREAD

**Issue by Arelav** [chaucerbao/stylelint-config-concentric-order#6]
Hello.
Is there any reason to lock dependency on Stylelint 9 only?
I have v10 installed for a long time and can't see any issues except the warning
`warning "stylelint-config-concentric-order > stylelint-order@0.8.1" has incorrect peer dependency "stylelint@^8.0.0 || ^9.0.0".`

**Comment by chaucerbao** [comment]
Oh hey, I apologize for not seeing this. I'm not getting notifications for some reason.

Anyway, I updated all dependencies and pushed a new minor-version.

**Comment by Arelav** [comment]
Thanks.
