### ISSUE TITLE
Add option to separate groups by new line

### ISSUE THREAD

**Issue by muuvmuuv** [chaucerbao/stylelint-config-concentric-order#9]
I thought that the groups are separate by a new line already because you linked to the concentric css guide but as I can see they are not.

Would be great to have an option for that. As you can see here, they are grouped with new lines: https://github.com/brandon-rhodes/Concentric-CSS/blob/master/style3.css

**Comment by cotneit** [comment]
Adding `emptyLineBefore: 'always'` to the src/index.js seems to do just that. The result is not pretty though, so you would probably want to use 'threshold' option for better flexibility.
Found it in [this part of stylelint-order docs](https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-order/README.md)

``` javascript
'order/properties-order': [
  groups.map(group => ({
    emptyLineBefore: 'always',
    properties: group
  }))
]
```

**Comment by cotneit** [comment]
Or, instead of creating a fork (which is completely unnecessary in this case), you can import this package inside your stylelint.config.js and map every property group with `emptyLineBefore: 'always'` property

```javascript
const propertiesOrder = require('stylelint-config-concentric-order').rules['order/properties-order'];

module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-config-concentric-order'],
  plugins: [
    'stylelint-order',
  ],
  rules: {
    'order/properties-order': propertiesOrder[0].map((group) => ({ properties: group.properties, emptyLineBefore: 'always' })),
  },
};
```

Note `propertiesOrder[0]`, I don't know the reason for it, but this config adds another array inside properties-order property.

**Comment by muuvmuuv** [comment]
I just forked it to add some custom properties and rules for our company. Thanks for the hint with importing and mapping them.
